### PR TITLE
Fix #18  Sanitize video title before download

### LINKED ISSUE #18: Video title contains illegal character ("/")  cause download failure
Trying to download a video title contains a backward slash and got an error in the console. The filename is treated as subpath and get "events.js:167 Uncaught Error: ENOENT: no such file or directory" error.

### PR DESCRIPTION
**Pull request by johnnyzh82**
Fixed #18 
1. Sanitize the video name before downloading
2. Added a reload button

### CODE REVIEW

**Comment by johnnyzh82** [comment]
#18

File: main.js [hunk 1]
```diff
@@ -37,6 +37,7 @@ function createWindow() {
         {
             label: 'Edit',
             submenu: [
+                {role: 'reload', accelerator: 'CmdOrCtrl+R', selector: 'reload:'},
```
Comment (leerob) [inline main.js]: Could this be capitalized?
```suggestion
                {role: 'Reload', accelerator: 'CmdOrCtrl+R', selector: 'reload:'},
```

Comment (johnnyzh82) [reply main.js]: Yes, it's case-insensitive.
